# Generated by Django 5.1.7 on 2025-04-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='uploads/files/covers'),
        ),
    ]
